from django.conf.urls import patterns, url, include
from opms.stats.views import *

urlpatterns = patterns('stats.views',
    # These URLS will all change!
    #(r'^report/pr/item/(?P<guid>.+)', 'pr_report3'),
    #(r'^report/pr/partial-guid/(?P<partial_guid>.+)', 'pr_report2'),
    #(r'^report/pr/(?P<sort_by>.*)', 'pr_report1'),

    # Pages in Stats
    (r'^report/summary/feeds/partial-guid/(?P<partial_guid>.+)', 'feed_detail'),
    (r'^report/summary/feeds/$', 'summary_feeds'),
#    # Temp hack CC pages for PR
#    (r'^report/summary/feeds-cc/partial-guid/(?P<partial_guid>.+)', 'feed_detail_cc'),
#    (r'^report/summary/feeds-cc/$', 'summary_feeds_cc'),

#    (r'^report/summary/items/(?P<guid>.+)$', 'item_detail'),
#    (r'^report/summary/items/$', 'summary_items'),
    (r'^report/summary/$', 'summary_index'),

    (r'report/authors/$', 'summary_authors'),

    # TODO: THIS NEEDS PULLING INTO ANOTHER APP!
    url(r'^monitors/url-scans/url-(?P<url_id>\d{1,5})$', urlmonitoring_url, name="url-scans-url"),
    url(r'^monitors/url-scans/task-(?P<task_id>\d{1,5})$', urlmonitoring_task, name="url-scans-task"),
    url(r'^monitors/url-scans/$', summary_urlmonitoring, name="url-scans-summary"),

    # Graphs generated by Stats
    (r'^graph/urlmonitoring/url_by_time/(?P<url_id>\d{1,5}).png', 'graph_urlmonitoring_url'),
    (r'^graph/apple/summary-total.png', 'graph_apple_summary_totals'),
    (r'^graph/apple/summary-feeds.png', 'graph_apple_summary_feeds'),
    (r'^graph/apple/feed_by_week/(?P<feed>.+).png', 'graph_apple_feed_weeks'),


    # Default page (aka, Stats home)
    (r'^$', 'index'),
)


# opmstree /
# |- admin/
# |- stats/
#    |- monitors/
#       |- url-scans/
#          |- url-{{url_id}}
#          |- task-{{task_id}}
#    |