from django.conf.urls.defaults import *

urlpatterns = patterns('stats.views',
    # These URLS will all change!
    #(r'^report/pr/item/(?P<guid>.+)', 'pr_report3'),
    #(r'^report/pr/partial-guid/(?P<partial_guid>.+)', 'pr_report2'),
    #(r'^report/pr/(?P<sort_by>.*)', 'pr_report1'),

    # Pages in Stats
    (r'^report/summary/feeds/partial-guid/(?P<partial_guid>.+)', 'feed_detail'),
    (r'^report/summary/feeds/$', 'summary_feeds'),
#    # Temp hack CC pages for PR
#    (r'^report/summary/feeds-cc/partial-guid/(?P<partial_guid>.+)', 'feed_detail_cc'),
#    (r'^report/summary/feeds-cc/$', 'summary_feeds_cc'),

#    (r'^report/summary/items/(?P<guid>.+)$', 'item_detail'),
#    (r'^report/summary/items/$', 'summary_items'),
    (r'^report/summary/$', 'summary_index'),

    (r'report/authors/$', 'summary_authors'),

    (r'^report/urlmonitoring/url/(?P<url_id>\d{1,5})$', 'urlmonitoring_url'),
    (r'^report/urlmonitoring/task/(?P<task_id>\d{1,5})$', 'urlmonitoring_task'),
    (r'^report/urlmonitoring/$', 'summary_urlmonitoring'),

    # Graphs generated by Stats
    (r'^graph/urlmonitoring/url_by_time/(?P<url_id>\d{1,5}).png', 'graph_urlmonitoring_url'),
    (r'^graph/apple/summary-total.png', 'graph_apple_summary_totals'),
    (r'^graph/apple/summary-feeds.png', 'graph_apple_summary_feeds'),
    (r'^graph/apple/feed_by_week/(?P<feed>.+).png', 'graph_apple_feed_weeks'),


    # Default page (aka, Stats home)
    (r'^$', 'index'),
)
