from django.conf.urls import patterns, url, include
from opms.monitors.views import *

urlpatterns = patterns('monitors.views',
    # Graphs generated by Stats
    url(r'^url-scans/graph/url_by_time/(?P<url_id>\d{1,5}).png', graph_urlmonitoring_url),
    # Pages in url-scans
    url(r'^url-scans/url-(?P<url_id>\d{1,5})$', urlmonitoring_url, name="url-scans-url"),
    url(r'^url-scans/task-(?P<task_id>\d{1,5})$', urlmonitoring_task, name="url-scans-task"),
    url(r'^url-scans/$', summary_urlmonitoring, name="url-scans-summary"),

    # Default page (aka, Monitors home)
    (r'^$', 'index'),
)